on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/update@v4.29.2
        with:
          classpath: "cicd/poc/changelogs"
          changeLogFile: "master.xml"
          driver: "org.postgresql.Driver"
          username: "liquibase"
          password: "liquibase-p0c"
          url: "jdbc:postgresql://liquibase-poc.cvosig2gs4mc.us-east-1.rds.amazonaws.com:5432/datavant"
